FROM node:alpine

WORKDIR app/

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

ARG DATABASE_URL="localdbstringNOTREQUIRED"
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]